export const LEAGUES = [
  {
    name: 'Serie A',
    country: 'Italy',
    icon: '/Bet_Website/images/leagues/serie_a.png',
  },
  {
    name: 'Premier League',
    country: 'England',
    icon: '/Bet_Website/images/leagues/premier_league.png',
  },
  {
    name: 'La Liga',
    country: 'Spain',
    icon: '/Bet_Website/images/leagues/la_liga.png',
  },
  {
    name: 'Bundesliga',
    country: 'Germany',
    icon: '/Bet_Website/images/leagues/bundesliga.png',
  },
  {
    name: 'Ligue 1',
    country: 'France',
    icon: '/Bet_Website/images/leagues/ligue_one.png',
  },
  {
    name: 'Champions League',
    country: 'Europe',
    icon: '/Bet_Website/images/leagues/champions_league.png',
  },
];

export const TEAMS = [
  // Serie A Teams
  {
    id: '1',
    name: 'Inter',
    league: 'Serie A',
    rating: 4.5,
    attack: 84,
    midfield: 83,
    defense: 82,
    logo: '/Bet_Website/images/teams/inter.png',
  },
  {
    id: '2',
    name: 'Milan',
    league: 'Serie A',
    rating: 4,
    attack: 82,
    midfield: 81,
    defense: 80,
    logo: '/Bet_Website/images/teams/milan.png',
  },
  {
    id: '3',
    name: 'Juventus',
    league: 'Serie A',
    rating: 4,
    attack: 81,
    midfield: 82,
    defense: 83,
    logo: '/Bet_Website/images/teams/juventus.png',
  },
  {
    id: '4',
    name: 'Napoli',
    league: 'Serie A',
    rating: 4,
    attack: 83,
    midfield: 82,
    defense: 81,
    logo: '/Bet_Website/images/teams/napoli.png',
  },
  {
    id: '5',
    name: 'Roma',
    league: 'Serie A',
    rating: 3.5,
    attack: 80,
    midfield: 79,
    defense: 78,
    logo: '/Bet_Website/images/teams/roma.png',
  },
  {
    id: '6',
    name: 'Lazio',
    league: 'Serie A',
    rating: 3.5,
    attack: 79,
    midfield: 78,
    defense: 77,
    logo: '/Bet_Website/images/teams/lazio.png',
  },
  {
    id: '7',
    name: 'Atalanta',
    league: 'Serie A',
    rating: 3.5,
    attack: 79,
    midfield: 78,
    defense: 77,
    logo: '/Bet_Website/images/teams/atalanta.png',
  },
  {
    id: '8',
    name: 'Fiorentina',
    league: 'Serie A',
    rating: 3.5,
    attack: 79,
    midfield: 78,
    defense: 77,
    logo: '/Bet_Website/images/teams/fiorentina.png',
  },
  {
    id: '9',
    name: 'Bologna',
    league: 'Serie A',
    rating: 3.3,
    attack: 75,
    midfield: 74,
    defense: 73,
    logo: '/Bet_Website/images/teams/bologna.png',
  },
  {
    id: '10',
    name: 'Sampdoria',
    league: 'Serie A',
    rating: 3.2,
    attack: 72,
    midfield: 71,
    defense: 70,
    logo: '/Bet_Website/images/teams/sampdoria.png',
  },

  // Premier League Teams
  {
    id: '11',
    name: 'Manchester United',
    league: 'Premier League',
    rating: 4.5,
    attack: 85,
    midfield: 82,
    defense: 80,
    logo: '/Bet_Website/images/teams/manchester_united.png',
  },
  {
    id: '12',
    name: 'Manchester City',
    league: 'Premier League',
    rating: 4.8,
    attack: 88,
    midfield: 85,
    defense: 84,
    logo: '/Bet_Website/images/teams/manchester_city.png',
  },
  {
    id: '13',
    name: 'Liverpool',
    league: 'Premier League',
    rating: 4.6,
    attack: 86,
    midfield: 83,
    defense: 81,
    logo: '/Bet_Website/images/teams/liverpool.png',
  },
  {
    id: '14',
    name: 'Chelsea',
    league: 'Premier League',
    rating: 4.2,
    attack: 82,
    midfield: 80,
    defense: 79,
    logo: '/Bet_Website/images/teams/chelsea.png',
  },
  {
    id: '15',
    name: 'Arsenal',
    league: 'Premier League',
    rating: 4.3,
    attack: 83,
    midfield: 81,
    defense: 78,
    logo: '/Bet_Website/images/teams/arsenal.png',
  },
  {
    id: '16',
    name: 'Tottenham Hotspur',
    league: 'Premier League',
    rating: 4.1,
    attack: 80,
    midfield: 79,
    defense: 77,
    logo: '/Bet_Website/images/teams/tottenham.png',
  },
  {
    id: '17',
    name: 'Leicester City',
    league: 'Premier League',
    rating: 3.9,
    attack: 78,
    midfield: 77,
    defense: 75,
    logo: '/Bet_Website/images/teams/leicester.png',
  },
  {
    id: '18',
    name: 'Everton',
    league: 'Premier League',
    rating: 3.7,
    attack: 76,
    midfield: 74,
    defense: 73,
    logo: '/Bet_Website/images/teams/everton.png',
  },

  // Bundesliga Teams
  {
    id: '19',
    name: 'Bayern Munich',
    league: 'Bundesliga',
    rating: 4.9,
    attack: 90,
    midfield: 85,
    defense: 86,
    logo: '/Bet_Website/images/teams/bayern_munich.png',
  },
  {
    id: '20',
    name: 'Borussia Dortmund',
    league: 'Bundesliga',
    rating: 4.4,
    attack: 84,
    midfield: 80,
    defense: 82,
    logo: '/Bet_Website/images/teams/dortmund.png',
  },
  {
    id: '21',
    name: 'RB Leipzig',
    league: 'Bundesliga',
    rating: 4.3,
    attack: 82,
    midfield: 81,
    defense: 80,
    logo: '/Bet_Website/images/teams/rb_leipzig.png',
  },
  {
    id: '22',
    name: 'Bayer Leverkusen',
    league: 'Bundesliga',
    rating: 4.2,
    attack: 83,
    midfield: 80,
    defense: 79,
    logo: '/Bet_Website/images/teams/bayer_leverkusen.png',
  },
  {
    id: '23',
    name: 'Wolfsburg',
    league: 'Bundesliga',
    rating: 4.0,
    attack: 80,
    midfield: 78,
    defense: 77,
    logo: '/Bet_Website/images/teams/wolfsburg.png',
  },

  // La Liga Teams
  {
    id: '24',
    name: 'Real Madrid',
    league: 'La Liga',
    rating: 4.8,
    attack: 89,
    midfield: 85,
    defense: 87,
    logo: '/Bet_Website/images/teams/real_madrid.png',
  },
  {
    id: '25',
    name: 'Barcelona',
    league: 'La Liga',
    rating: 4.7,
    attack: 88,
    midfield: 84,
    defense: 85,
    logo: '/Bet_Website/images/teams/barcelona.png',
  },
  {
    id: '26',
    name: 'Atletico Madrid',
    league: 'La Liga',
    rating: 4.6,
    attack: 87,
    midfield: 83,
    defense: 84,
    logo: '/Bet_Website/images/teams/atletico_madrid.png',
  },
  {
    id: '27',
    name: 'Sevilla',
    league: 'La Liga',
    rating: 4.3,
    attack: 80,
    midfield: 79,
    defense: 78,
    logo: '/Bet_Website/images/teams/sevilla.png',
  },
  {
    id: '28',
    name: 'Villarreal',
    league: 'La Liga',
    rating: 4.1,
    attack: 78,
    midfield: 77,
    defense: 76,
    logo: '/Bet_Website/images/teams/villareal.png',
  },

  // Ligue 1 Teams
  {
    id: '29',
    name: 'Paris Saint-Germain',
    league: 'Ligue 1',
    rating: 4.7,
    attack: 87,
    midfield: 84,
    defense: 82,
    logo: '/Bet_Website/images/teams/psg.png',
  },
  {
    id: '30',
    name: 'Lyon',
    league: 'Ligue 1',
    rating: 4.1,
    attack: 82,
    midfield: 80,
    defense: 78,
    logo: '/Bet_Website/images/teams/lyon.png',
  },
  {
    id: '31',
    name: 'Marseille',
    league: 'Ligue 1',
    rating: 4.0,
    attack: 80,
    midfield: 79,
    defense: 77,
    logo: '/Bet_Website/images/teams/marseille.png',
  },
  {
    id: '32',
    name: 'Monaco',
    league: 'Ligue 1',
    rating: 3.9,
    attack: 79,
    midfield: 77,
    defense: 75,
    logo: '/Bet_Website/images/teams/monaco.png',
  },
  {
    id: '33',
    name: 'Bayern Munich',
    league: 'Champions League',
    rating: 4.9,
    attack: 90,
    midfield: 85,
    defense: 86,
    logo: '/Bet_Website/images/teams/bayern_munich.png',
  },
  {
    id: '34',
    name: 'Real Madrid',
    league: 'Champions League',
    rating: 4.8,
    attack: 89,
    midfield: 85,
    defense: 87,
    logo: '/Bet_Website/images/teams/real_madrid.png',
  },
  {
    id: '35',
    name: 'Barcelona',
    league: 'Champions League',
    rating: 4.7,
    attack: 88,
    midfield: 84,
    defense: 85,
    logo: '/Bet_Website/images/teams/barcelona.png',
  },
  {
    id: '36',
    name: 'Chelsea',
    league: 'Champions League',
    rating: 4.2,
    attack: 82,
    midfield: 80,
    defense: 79,
    logo: '/Bet_Website/images/teams/chelsea.png',
  },
  {
    id: '37',
    name: 'Inter',
    league: 'Champions League',
    rating: 4.2,
    attack: 82,
    midfield: 80,
    defense: 79,
    logo: '/Bet_Website/images/teams/inter.png',
  },
  {
    id: '38',
    name: 'Milan',
    league: 'Champions League',
    rating: 4.2,
    attack: 82,
    midfield: 80,
    defense: 79,
    logo: '/Bet_Website/images/teams/milan.png',
  },
  {
    id: '39',
    name: 'Paris Saint-Germain',
    league: 'Champions League',
    rating: 4.7,
    attack: 87,
    midfield: 84,
    defense: 82,
    logo: '/Bet_Website/images/teams/psg.png',
  },
  {
    id: '40',
    name: 'Manchester City',
    league: 'Champions League',
    rating: 4.8,
    attack: 88,
    midfield: 85,
    defense: 84,
    logo: '/Bet_Website/images/teams/manchester_city.png',
  },
];

